# -*- coding: utf-8 -*-
"""decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdbwhDo6xpz4d0wA8uWPzd5hGfbS2BIq
"""

# Importing all the required libraries that will be used throughout this project.
# Pandas is used for handling and analysing data, NumPy is used for numerical operations
# Matplotlib and Seaborn are used for data visualisation.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# From sklearn, we import tools needed for splitting data, building the model,and evaluating its performance.
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Loading the dataset from a CSV file into a pandas DataFrame.

df = pd.read_csv("bank-full.csv")

# Displaying the first few rows of the dataset to get a quick understanding
df.head()

# Checking the basic structure of the dataset such as data types, number of non-null values, and overall size of the dataset.
df.info()
df.describe()

# Visualising the distribution of the target variable 'y'.
# This helps us understand whether the dataset is balanced or imbalanced,
# meaning whether there are similar numbers of 'yes' and 'no' outcomes.
sns.countplot(x='y', data=df)
plt.title("Target Variable Distribution")
plt.show()

# Converting the target variable from categorical values ('yes' and 'no')
# into numerical format (1 and 0). This is required because machine learning models work with numerical data, not text
df['y'] = df['y'].map({'yes': 1, 'no': 0})

# Converting all categorical features into numerical form using one-hot encoding

df_encoded = pd.get_dummies(df, drop_first=True)

# Separating the dataset into input features (X) and the target variable (y)

X = df_encoded.drop('y', axis=1)
y = df_encoded['y']

# Splitting the dataset into training and testing sets.
# The model is trained on 80% of the data and tested on the remaining 20%
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

# Defining a function to calculate entropy, which is a measure of impurity.

def entropy(p):
    return -p*np.log2(p) - (1-p)*np.log2(1-p)

p = np.linspace(0.01, 0.99, 100)
ent = entropy(p)

plt.plot(p, ent)
plt.title("Entropy Curve")
plt.xlabel("Probability")
plt.ylabel("Entropy")
plt.show()

# Training the model with the dataset

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

# Making Prediction with test data on behalf of trained data

y_pred = model.predict(X_test)

# Here we evaluate how well the trained model performs on unseen data.
# Accuracy measures the overall percentage of correct predictions.

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# The classification report provides deeper insights into model performance.
# It includes precision (how many predicted positives are correct),
# recall (how many actual positives are correctly predicted),
# and F1-score (balance between precision and recall).

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# A confusion matrix is created to compare actual vs predicted values.

cm = confusion_matrix(y_test, y_pred)

# Visualising the confusion matrix using a heatmap makes it easier to interpret.
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Plotting the decision tree helps us understand how the model makes decisions.
# Each node represents a condition, and branches represent outcomes.

plt.figure(figsize=(20,10))
plot_tree(model, filled=True, feature_names=X.columns, class_names=["No", "Yes"])
plt.show()

# Extracting feature importance values from the trained model.

importances = model.feature_importances_

# Converting feature importance into a pandas Series for easier sorting and display.
feat_imp = pd.Series(importances, index=X.columns).sort_values(ascending=False)[:10]

# Plotting the top features to visually understand which variables influence the model most.
feat_imp.plot(kind='barh')
plt.title("Top 10 Feature Importances")
plt.show()

# Testing different tree depths to see how model performance changes.

depths = [2, 3, 5, 10, 15]
train_acc = []
test_acc = []

# Looping through different depth values and training separate models.
for d in depths:
    temp_model = DecisionTreeClassifier(max_depth=d, random_state=42)
    temp_model.fit(X_train, y_train)

    train_acc.append(temp_model.score(X_train, y_train))
    test_acc.append(temp_model.score(X_test, y_test))

plt.plot(depths, train_acc, label="Train Accuracy")
plt.plot(depths, test_acc, label="Test Accuracy")
plt.xlabel("Depth")
plt.ylabel("Accuracy")
plt.legend()
plt.title("Depth vs Accuracy")
plt.show()

# Overfitting view
# This graph focuses specifically on visualising overfitting.
# If training accuracy is very high but testing accuracy drops,
# it indicates that the model is memorising data instead of learning patterns.

plt.plot(depths, train_acc, marker='o')
plt.plot(depths, test_acc, marker='o')

plt.title("Overfitting Analysis")
plt.xlabel("Tree Depth")
plt.ylabel("Accuracy")
plt.legend(["Train", "Test"])
plt.show()

# Selecting a single sample from the test dataset.

sample = X_test.iloc[0].values.reshape(1, -1)

# Using the trained model to predict the output for this sample
prediction = model.predict(sample)

print("Prediction:", prediction)